# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a 4x4 identity matrix
NULL

mat4_create <- function() {
    .Call(`_gazeneuro_mat4_create`)
}

mat4_clone <- function(a) {
    .Call(`_gazeneuro_mat4_clone`, a)
}

mat4_transpose <- function(a) {
    .Call(`_gazeneuro_mat4_transpose`, a)
}

mat4_invert <- function(a) {
    .Call(`_gazeneuro_mat4_invert`, a)
}

mat4_translate <- function(a, v) {
    .Call(`_gazeneuro_mat4_translate`, a, v)
}

mat4_scale_columns_directly <- function(mat, dim) {
    .Call(`_gazeneuro_mat4_scale_columns_directly`, mat, dim)
}

vec4_transformMat4 <- function(a, m) {
    .Call(`_gazeneuro_vec4_transformMat4`, a, m)
}

print_glmatrix <- function(mat) {
    invisible(.Call(`_gazeneuro_print_glmatrix`, mat))
}

